MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
NKRO_ENABLE = yes
TRI_LAYER_ENABLE = yes

COMMAND_ENABLE = no
CONSOLE_ENABLE = no
ENCODER_ENABLE = yes
OLED_ENABLE = yes

ENCODER_MAP_ENABLE = yes

WPM_ENABLE = yes

#BACKLIGHT_ENABLE = no
#RGBLIGHT_ENABLE = yes
